/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapAnimeDotxmlRouteImport } from './routes/sitemap-anime[.]xml'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as SitemapMoviesDotxmlRouteImport } from './routes/sitemap-movies[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestRouteImport } from './routes/test'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AnimeIndexRouteImport } from './routes/anime.index'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BlogBestAnimeWebsitesRouteImport } from './routes/blog.best-anime-websites'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapAnimeDotxmlRoute = SitemapAnimeDotxmlRouteImport.update({
  id: '/sitemap-anime.xml',
  path: '/sitemap-anime.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapMoviesDotxmlRoute = SitemapMoviesDotxmlRouteImport.update({
  id: '/sitemap-movies.xml',
  path: '/sitemap-movies.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBestAnimeWebsitesRoute = BlogBestAnimeWebsitesRouteImport.update({
  id: '/blog/best-anime-websites',
  path: '/blog/best-anime-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap-anime.xml': typeof SitemapAnimeDotxmlRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test': typeof TestRoute
  '/wishlist': typeof WishlistRoute
  '/anime/$id': typeof AnimeIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/best-anime-websites': typeof BlogBestAnimeWebsitesRoute
  '/watch/$id': typeof WatchIdRoute
  '/anime/': typeof AnimeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap-anime.xml': typeof SitemapAnimeDotxmlRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test': typeof TestRoute
  '/wishlist': typeof WishlistRoute
  '/anime/$id': typeof AnimeIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/best-anime-websites': typeof BlogBestAnimeWebsitesRoute
  '/watch/$id': typeof WatchIdRoute
  '/anime': typeof AnimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap-anime.xml': typeof SitemapAnimeDotxmlRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test': typeof TestRoute
  '/wishlist': typeof WishlistRoute
  '/anime/$id': typeof AnimeIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/best-anime-websites': typeof BlogBestAnimeWebsitesRoute
  '/watch/$id': typeof WatchIdRoute
  '/anime/': typeof AnimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/movies'
    | '/profile'
    | '/search'
    | '/sitemap-anime.xml'
    | '/sitemap-blog.xml'
    | '/sitemap-movies.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/test'
    | '/wishlist'
    | '/anime/$id'
    | '/auth/callback'
    | '/blog/best-anime-websites'
    | '/watch/$id'
    | '/anime/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/movies'
    | '/profile'
    | '/search'
    | '/sitemap-anime.xml'
    | '/sitemap-blog.xml'
    | '/sitemap-movies.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/test'
    | '/wishlist'
    | '/anime/$id'
    | '/auth/callback'
    | '/blog/best-anime-websites'
    | '/watch/$id'
    | '/anime'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/movies'
    | '/profile'
    | '/search'
    | '/sitemap-anime.xml'
    | '/sitemap-blog.xml'
    | '/sitemap-movies.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/test'
    | '/wishlist'
    | '/anime/$id'
    | '/auth/callback'
    | '/blog/best-anime-websites'
    | '/watch/$id'
    | '/anime/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MoviesRoute: typeof MoviesRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SitemapAnimeDotxmlRoute: typeof SitemapAnimeDotxmlRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapMoviesDotxmlRoute: typeof SitemapMoviesDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestRoute: typeof TestRoute
  WishlistRoute: typeof WishlistRoute
  AnimeIdRoute: typeof AnimeIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogBestAnimeWebsitesRoute: typeof BlogBestAnimeWebsitesRoute
  WatchIdRoute: typeof WatchIdRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-anime.xml': {
      id: '/sitemap-anime.xml'
      path: '/sitemap-anime.xml'
      fullPath: '/sitemap-anime.xml'
      preLoaderRoute: typeof SitemapAnimeDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-movies.xml': {
      id: '/sitemap-movies.xml'
      path: '/sitemap-movies.xml'
      fullPath: '/sitemap-movies.xml'
      preLoaderRoute: typeof SitemapMoviesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-anime-websites': {
      id: '/blog/best-anime-websites'
      path: '/blog/best-anime-websites'
      fullPath: '/blog/best-anime-websites'
      preLoaderRoute: typeof BlogBestAnimeWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MoviesRoute: MoviesRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SitemapAnimeDotxmlRoute: SitemapAnimeDotxmlRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapMoviesDotxmlRoute: SitemapMoviesDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestRoute: TestRoute,
  WishlistRoute: WishlistRoute,
  AnimeIdRoute: AnimeIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogBestAnimeWebsitesRoute: BlogBestAnimeWebsitesRoute,
  WatchIdRoute: WatchIdRoute,
  AnimeIndexRoute: AnimeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
